version: "3"

volumes:
  postgres_global_motters_volume:

services:
  pg_auth:
    image: postgres:14-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_global_motters_volume:/var/lib/postgresql/data
  auto_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - pg_auth